spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost/upsideavenue
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        